dependencies {
    // Modules
    implementation(project(":core:design_system"))
    implementation(project(":core:navigation"))
    implementation(project(":core:data"))
    implementation(project(":core:domain"))
    implementation(project(":features:onboarding"))
    implementation(project(":features:home"))
    implementation(project(":features:favorites"))
    implementation(project(":features:shopping_cart"))
    implementation(project(":features:product_details"))
    implementation(project(":features:settings"))
    implementation(project(":feature:auth"))
    implementation(project(":features:search"))
    implementation(project(":feature:address"))
    implementation(project(":features:categories"))
    implementation(project(":feature:ads"))
    implementation(project(":core:payment"))

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.serialization.json)
    implementation(platform(libs.firebase.bom))
    implementation(libs.navigation.compose)
    implementation(libs.hilt.navigation.compose)

    // Required for Paymob SDK resource linking
    implementation(libs.sdp)
    implementation(libs.ssp)
    implementation(libs.androidx.navigation.fragment.ktx)
    implementation(libs.androidx.navigation.ui.ktx)

    testImplementation(libs.junit)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)

    debugImplementation(libs.androidx.compose.ui.test.manifest)
    debugImplementation(libs.androidx.compose.ui.tooling)
}