query CollectionProducts(
    $id: ID!
    $first: Int!
    $after: String
    $country: CountryCode!
    $language: LanguageCode!
) @inContext(country: $country, language: $language) {
    collection(id: $id) {
        id
        title
        products(first: $first, after: $after) {
            edges {
                cursor
                node {
                    id
                    title
                    productType
                    description
                    featuredImage {
                        url
                        thumbhash
                    }
                    priceRange {
                        minVariantPrice {
                            amount
                            currencyCode
                        }
                        maxVariantPrice {
                            amount
                            currencyCode
                        }
                    }
                    metafields(identifiers: [{ namespace: "reviews", key: "items" }]) {
                        key
                        namespace
                        value
                        type
                        references(first: 50) {
                            edges {
                                node {
                                    ... on Metaobject {
                                        id
                                        rating: field(key: "rating") { value }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            pageInfo {
                hasNextPage
                endCursor
            }
        }
    }
}