query CollectionProducts(
    $handle: String!
    $first: Int!
    $after: String
    $country: CountryCode!
    $language: LanguageCode!
) @inContext(country: $country, language: $language) {
    collection(handle: $handle) {
        id
        title
        products(first: $first, after: $after) {
            edges {
                cursor
                node {
                    id
                    title
                    productType
                    description
                    featuredImage {
                        url
                        thumbhash
                    }
                    priceRange {
                        minVariantPrice {
                            amount
                            currencyCode
                        }
                        maxVariantPrice {
                            amount
                            currencyCode
                        }
                    }
                }
            }
            pageInfo {
                hasNextPage
                endCursor
            }
        }
    }
}