query GetProductsByVendor(
    $query: String!
    $first: Int!
    $after: String
    $country: CountryCode
    $language: LanguageCode
) @inContext(country: $country, language: $language) {
    products(query: $query, first: $first, after: $after) {
        edges {
            node {
                id
                title
                featuredImage {
                    url
                    thumbhash
                }
                priceRange {
                    minVariantPrice {
                        amount
                        currencyCode
                    }
                    maxVariantPrice {
                        amount
                        currencyCode
                    }
                }
                metafields(identifiers: [{ namespace: "reviews", key: "items" }]) {
                    key
                    namespace
                    value
                    type
                    references(first: 50) {
                        edges {
                            node {
                                ... on Metaobject {
                                    id
                                    rating: field(key: "rating") { value }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}