query PredictiveSearch($query: String! = "sne") {
    predictiveSearch(query: $query, types: [PRODUCT, COLLECTION]) {
        products {
            id
            title
            vendor
            productType
            availableForSale
            priceRange {
                minVariantPrice {
                    amount
                    currencyCode
                }
            }
            featuredImage {
                url
                altText
            }
            metafields(identifiers: [{ namespace: "reviews", key: "items" }]) {
                key
                namespace
                value
                type
                references(first: 50) {
                    edges {
                        node {
                            ... on Metaobject {
                                id
                                rating: field(key: "rating") { value }
                            }
                        }
                    }
                }
            }
        }
        collections {
            id
            title
            handle
            image {
                url
            }
        }
    }
}
