query Products($first: Int = 10, $after: String) {
    products(first: $first, after: $after) {
        pageInfo {
            hasNextPage
            endCursor
        }
        edges {
            node {
                id
                handle
                title
                description
                featuredImage {
                    url
                    thumbhash
                }
                priceRange {
                    maxVariantPrice { amount currencyCode }
                    minVariantPrice { amount currencyCode }
                }
            }
        }
    }
}