query ProductQuery($id: ID!) {
    product(id: $id) {
        id
        title
        handle
        featuredImage {
            altText
            url
            thumbhash
        }
        productType
        priceRange {
            maxVariantPrice {
                amount
                currencyCode
            }
            minVariantPrice {
                amount
                currencyCode
            }
        }
        description
        images(first: 20) {
            nodes {
                altText
                url
                thumbhash
            }
        }
        variants(first: 10) {
            nodes {
                availableForSale
                currentlyNotInStock
                id
                quantityAvailable
                title
                image {
                    altText
                    url
                    thumbhash
                }
                price {
                    amount
                    currencyCode
                }
            }
        }
    }
}
